### ISSUE TITLE
pwd of KS20 under Dataset.zip

### ISSUE THREAD

**Issue by linhuaiyi** [Kali-Hac/SimMC#1]
what the password of KS20 under Dataset.zip?

**Comment by Kali-Hac** [comment]
As shown in our repository,

"The access to the Vislab Multi-view KS20 dataset and large-scale RGB-based gait dataset CASIA-B are available upon request. If you have signed the license agreement and been granted the right to use them, please email us with the signed agreement and we will share the complete pre-processed KS20 and CASIA-B data. "

So please sign the license agreement and email it to us. Thank you.
